sudo: required
group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-jmx4perl .
  - docker run --detach --name jmx4perl bodsch/docker-jmx4perl

script:
  - true

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-jmx4perl/trigger/${DOCKER_HUB_TOKEN}/
