sudo: required
group: edge
services:
- docker
jobs:
  include:
  - stage: build, test and push docker image
    script:
    - make build
    - docker-compose --file docker-compose-example.yml up --build -d
    - docker-compose --file docker-compose-example.yml kill
    - docker-compose --file docker-compose-example.yml down
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker push ${DOCKER_USERNAME}/docker-jmx4perl:latest
    - docker logout
env:
  global:
  - DOCKER_USERNAME: bodsch
  - secure: UsKiLyKr46iHmvmt/TR0S5tTnKmwMNwzU9omUP6sRBRhoT2SPegdOpYChAhuqZPcPfHx0Lh94eHEzmVivnMifQCIV4MHvgTZWydOXeSwysAWEWoF3eZyExgp9tCaSaIR3YYn8l6tNe3oMvoMoqt2LS7dXrklLyp9ldnZpeUsJW/GaS323EVU3RxXsXuRZL6ITXr9BtFZo5PUO2ojkzamGgORIQ4nyohjUcZxbUS3ZgTLWwg0SIaO/KAeMwRncHIZ61QtHc4Rha1x18ZZveu1b+xQc/F1bjcWkdrCrDSoCgDb2/Tmn/nhDvvTFqhkG/mC5v6pzlprcAE7n4FJB6gUsPMPIIuk0R5ylnt7dN1oxnEv4Xjp+4IZRGmPNqWmJ5TO/EAP/DU4hI8vHpeFs6tgBkbKhR4f2qsHirRmCNx6RU37VYnVW8BMnSO37ZxVGVShW1ZASwsqCiJGVnduZdsVAla1PGLwvlq2OfvDUizx7S/WyDyUJJURAf4E1wKA1237A/h3mmmlgaQRdh7INvveC0WdPCIn+TunQqw6rkwRz91jJwA9HRsEPO7UQeIq5xEvqFJ3RCeSFSDESY1avyrxLkbyTpJ4gsOptMUqAGrcuMVpqmWnx1hevoPV16Y/tV4nyUtsGtRb//iueXpPQKwhmShUl6gM3Gfz/Xj20+PgDJE=
  - secure: LakVSN0J5mUyd8ou/f3hmmt2uCQjz7pyq5Vn4OcspW7IOV7H2DczUPJIQqqCLZRzuFaOPrGo8FFWsCVfnOvjs7oFaIuP3sSgHDeA09d7T2QR5voF0YCxnETP9cSmKMskqQ+CJk3ZYyxzDtN/j8uStQAiDgifO9f9UTiHuxfkrJEhmR5GzB7w9vED1EK1P1MVb5Qh5S1Vi2E4sdDklyGFYph7EJ6/1Z1AXm2vvkfaZ0bnCW7HSOkB2exh6qGWaMGgYO89WezcWXB3AM/6NS/CW0I31GmtYxgyUhQL3erTytUeCOe/ixAhp3S7b7gGlKEPSS1NaQ9WkCB6BVJ2jiXN9PJJPQdAgpAX/eH89KZtX5g990bhN7VT1ynJSHdIQERQozMgf0aXoF4w8oJ6AP05wOabmL2UgF6m8JKFOnmCU7y2fhWwyE3wsJgH9krGCg/J5h82ltwuwzDX6SflcecuMcmTuFXgu7HyISshqP0a9BqP1N+bDpLGHMDVKxNFoopu3wPPQEGGhpCmtrTh1LRRX7kBQFi8jjxJ44zeMeH5fZCuPIyKfRbjsDBw6M5wI3+5GPucTYy4bZePbrLVnd9O545IoYUXXB83HPHRgIvnsnV1TYQCbC7wka1numwF4C+m0cdFKWwyAfy3ITewmqUeur3rneqa993m9HAAqnOi9HI=
